if(preprocessor_ROOT)
    include(CMakePrintHelpers)
    set(preprocessor_INCLUDE_DIRS ${preprocessor_ROOT}/include)
    set(preprocessor_LIBRARIES)
    if(USE_EXTERNAL_BOOST)
	  find_package(Boost)
      cmake_print_variables(Boost_FOUND)
      if(Boost_FOUND)
        list(APPEND preprocessor_LIBRARIES Boost::headers)
      endif()
    endif()
    set(preprocessor_FOUND TRUE)
    if(NOT TARGET preprocessor::preprocessor)
      add_library(preprocessor_header_only INTERFACE)
      add_library(preprocessor::preprocessor ALIAS preprocessor_header_only)
      list(APPEND apply::apply preprocessor_LIBRARIES preprocessor::preprocessor)
      set_target_properties(preprocessor_header_only PROPERTIES
        INTERFACE_INCLUDE_DIRECTORIES "${preprocessor_INCLUDE_DIRS}"
        INTERFACE_LINK_LIBRARIES "${preprocessor_LIBRARIES}"
      )
    endif()
    cmake_print_variables(preprocessor_INCLUDE_DIRS)
    cmake_print_variables(preprocessor_LIBRARIES)
endif()
